#################################################################
## Home Assistant - Core Configuration
#################################################################

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret secret_latitude
  longitude: !secret secret_longitude
  elevation: !secret secret_elevation
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml

# Enables the frontend
frontend:
  extra_html_url:
    - /local/hass-bha-icons.html

# Checks for available updates
updater:
  reporting: no

# Track the sun
sun:

# Discovery of devices automatically if supported
discovery:
  ignore:
    - samsung_tv
    - apple_tv

# Config options for system and discovery devices
config:
person:
system_health:
mobile_app:
ssdp:
zeroconf:
http:
  base_url: !secret secret_base_url
  ssl_certificate: !secret secret_ssl_certificate
  ssl_key: !secret secret_ssl_key


#################################################################
## Components
#################################################################

# Custom Logging Setting

#logger:
#  default: info
#  logs:
#    aiounifi: debug
#    homeassistant.components.unifi: debug
#    homeassistant.components.device_tracker.unifi: debug
#    homeassistant.components.switch.unifi: debug

hue:
  bridges:
  - host: REDACTED.32
    allow_unreachable: true
    allow_hue_groups: false

emulated_hue:
  host_ip: REDACTED.100
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false

remote:
  - platform: harmony
    name: Media Center
    host: REDACTED.12

map:

# Enables support for tracking state changes over time.
history:


# InfluxDB / Grafana Long Term Data Retention Test
influxdb:
  host: REDACTED.196
  include:
    entities:
      - sensor.home_temperature
      - sensor.master_bedroom_temperature
      - sensor.basement_temperature
      - sensor.USER3_bedroom_temperature
      - sensor.USER4_bedroom_temperature
      - sensor.home_humidity
      - sensor.dark_sky_humidity
      - sensor.dark_sky_temperature
      - sensor.thermostat_current_status
      - sensor.thermostat_aux_heat
      - sensor.ups_load
      - sensor.nas_cpu_usage
      - sensor.nas_memory_usage
      - sensor.nas_volume_used_storage
      - sensor.nas_volume_used_backup
      - sensor.nas_system_temperature
      - sensor.ring_front_door_battery
      - sensor.basement_door_battery
      - sensor.basement_motion_battery
      - sensor.pantry_door_battery
      - sensor.basement_water_sensor_battery
      - sensor.washing_machine_current_power
      - sensor.air_cleaner_current_power
      - sensor.nanopool_hashrate
      - sensor.nanopool_balance
      - binary_sensor.wan
      - binary_sensor.gateway

# Unifi Presence Detection
#unifi:
#  controllers:
#    - host: REDACTED.3
#      site: Home
#      ssid_filter:
#        - 'REDACTED Home 2'

# VeraPlus controller to replace wink
vera:
  vera_controller_url: http://REDACTED.140:3480/

# Stream Componant
stream:

# WeMo
wemo:
  static:
    - REDACTED.188
    - REDACTED.198
    - REDACTED.148

# Weather
weather:
  - platform: darksky
    api_key: !secret secret_darksky_api_key
    mode: daily

#goalfeed:
#  username: !secret secret_goalfeed_username
#  password: !secret secret_goalfeed_password

## Lutron Caseta bridge
lutron_caseta:
    host: REDACTED.141
    keyfile: !secret secret_lutron_keyfile
    certfile: !secret secret_lutron_certfile
    ca_certs: !secret secret_lutron_cacerts

vacuum:
  - platform: roomba
    host: REDACTED.150
    username: !secret secret_roomba_username
    password: !secret secret_roomba_password
    name: Roomba

ecobee:
  api_key: !secret secret_ecobee_apikey
  hold_temp: true

# Ring
ring:
    username: !secret secret_ring_username
    password: !secret secret_ring_password

# Nest
nest:
  client_id: !secret secret_nest_clientid
  client_secret: !secret secret_nest_secret

################################################################
## Media Players
################################################################

media_player:
  - platform: plex
    entity_namespace: 'plex'

#apple_tv:
#  - name: Master Bedroom Apple TV
#    host: REDACTED.23
#    login_id: !secret secret_apple_tv_login_id
#    start_off: false
#  - name: Basement Apple TV
#    host: REDACTED.17
#    login_id: !secret secret_apple_tv_login_id
#    start_off: false
#  - name: Family Room Apple TV
#    host: REDACTED.65
#    login_id: !secret secret_apple_tv_login_id
#    credentials: !secret secret_apple_tv_family_room_credentials
#    start_off: false

#################################################################
## Zones
#################################################################

zone :

  name: REDACTED
  latitude: !secret secret_REDACTED_latitude
  longitude: !secret secret_REDACTED_longitude
  radius: 350
  icon: mdi:REDACTED

zone 2:

  name: REDACTED
  latitude: !secret secret_REDACTED_latitude
  longitude: !secret secret_REDACTED_longitude
  radius: 250
  icon: mdi:REDACTED

zone 3:

  name: REDACTED
  latitude: !secret secret_hms_latitude
  longitude: !secret secret_hms_longitude
  radius: 250
  icon: mdi:REDACTED

zone 4:

  name: REDACTED Home
  latitude: !secret secret_REDACTED_home_latitude
  longitude: !secret secret_REDACTED_home_longitude
  radius: 250
  icon: mdi:home

#################################################################
## Alarm Panel - Envisalink-DSC
#################################################################

envisalink:
#optional
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30
#required
  host: !secret secret_envisalink_host
  panel_type: DSC
  user_name: !secret secret_alarm_user_name
  password: !secret secret_alarm_password
  code: !secret secret_alarm_code

  zones:
    1:
      name: 'Garage Entry Door'
      type: 'opening'

    2:
      name: 'Garage Back Door'
      type: 'opening'

    3:
      name: 'Front Door'
      type: 'opening'

    4:
      name: 'Back Door'
      type: 'opening'


  partitions:
    1:
      name: 'Home Alarm'

input_number:
  goalfeed:
    name: Goalfeed Delay
    initial: 1
    min: 0
    max: 180
    step: 1

######## INCLUDES ########
automation: !include_dir_merge_list automation
logbook: !include logbook.yaml
recorder: !include recorder.yaml
group: !include groups.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include camera.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
light: !include light_group.yaml
script: !include scripts.yaml
scene: !include_dir_merge_list scene
ios: !include ios.yaml
switch: !include switch.yaml
