## Based on config originally from geekofweek

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret secret_latitude
  longitude: !secret secret_longitude
  elevation: !secret secret_elevation
  unit_system: imperial

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml


config:

http:
  api_password: !secret secret_api_password
  base_url: !secret secret_base_url
  ssl_certificate: !secret secret_ssl_certificate
  ssl_key: !secret secret_ssl_key

# Enables the frontend
frontend:

# Checks for available updates
updater:
  reporting: no

# Track the sun
sun:

# Discover some devices automatically
discovery:
 ignore:
   - samsung_tv
   - apple_tv

map:

# Custom Logging Setting
#logger:
# Enables support for tracking state changes over time.
history:

#################################################################
## Components
#################################################################

hue:
  bridges:
  - host: REDACTED.32
    allow_unreachable: false
    allow_hue_groups: false

remote:
  - platform: harmony
    name: Media Center
    host: REDACTED.12

# InfluxDB / Grafana Long Term Data Retention Test
influxdb:
  host: REDACTED.100
  include:
    entities:
      - sensor.home_temperature
      - sensor.master_bedroom_temperature
      - sensor.basement_temperature
      - sensor.USER3_bedroom_temperature
      - sensor.USER4_bedroom_temperature
      - sensor.home_humidity
      - sensor.dark_sky_humidity
      - sensor.dark_sky_temperature
      - sensor.thermostat_current_status
      - sensor.thermostat_aux_heat
      - sensor.ups_load
      - sensor.nas_cpu_usage
      - sensor.nas_memory_usage
      - sensor.nas_volume_used_storage
      - sensor.nas_volume_used_backup
      - sensor.nas_system_temperature
      - sensor.ring_front_door_battery
      - sensor.basement_door_battery
      - sensor.basement_motion_battery
      - sensor.pantry_door_battery
      - sensor.basement_water_sensor_battery
      - sensor.washing_machine_current_power

# Wink Hub
wink:

# WeMo
wemo:

vacuum:
  - platform: roomba
    host: REDACTED.184
    username: !secret secret_roomba_username
    password: !secret secret_roomba_password
    name: Roomba

ecobee:
  api_key: !secret secret_ecobee_apikey
  hold_temp: true

# Ring
ring:
    username: !secret secret_ring_username
    password: !secret secret_ring_password

# Nest
nest:
  client_id: !secret secret_nest_clientid
  client_secret: !secret secret_nest_secret

device_tracker:
  - platform: locative
    track_new_devices: no
    interval_seconds: 12
    consider_home: 180
  - platform: unifi
    username: !secret secret_unifi_username
    password: !secret secret_unifi_password
    host: !secret secret_unifi_host
    verify_ssl: false
    consider_home: 180
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

notify:
  - name: hass_sns
    platform: aws_sns
    aws_access_key_id: !secret secret_aws_access_key_id
    aws_secret_access_key: !secret secret_aws_secret_access_key
    region_name: 'us-east-1'

ios:

################################################################
## Media Players
################################################################
 media_player:
  - platform: plex
    entity_namespace: 'plex'

#apple_tv:
#  - name: Master Bedroom Apple TV
#    host: REDACTED.23
#    login_id: !secret secret_apple_tv_login_id
#    start_off: false
#  - name: Basement Apple TV
#    host: REDACTED.17
#    login_id: !secret secret_apple_tv_login_id
#    start_off: false
#  - name: Family Room Apple TV
#    host: REDACTED.65
#    login_id: !secret secret_apple_tv_login_id
#    credentials: !secret secret_apple_tv_family_room_credentials
#    start_off: false
#################################################################
## Zones
#################################################################

zone :

  name: REDACTED
  latitude: !secret secret_REDACTED_latitude
  longitude: !secret secret_REDACTED_longitude
  radius: 350
  icon: mdi:REDACTED

zone 2:

  name: REDACTED
  latitude: !secret secret_REDACTED_latitude
  longitude: !secret secret_REDACTED_longitude
  radius: 250
  icon: mdi:REDACTED

zone 3:

  name: REDACTED
  latitude: !secret secret_hms_latitude
  longitude: !secret secret_hms_longitude
  radius: 250
  icon: mdi:REDACTED

#zone 4:

#  name: REDACTED
#  latitude: !secret secret_REDACTED_latitude
#  longitude: !secret secret_REDACTED_longitude
#  radius: 250
#  icon: mdi:office-building

zone 4:

  name: REDACTED Home
  latitude: !secret secret_REDACTED_home_latitude
  longitude: !secret secret_REDACTED_home_longitude
  radius: 250
  icon: mdi:home


#################################################################
## Alarm Panel - Envisalink-DSC
#################################################################

envisalink:
#optional
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30

#required
  host: !secret secret_envisalink_host
  panel_type: DSC
  user_name: !secret secret_alarm_user_name
  password: !secret secret_alarm_password
  code: !secret secret_alarm_code

  zones:
    1:
      name: 'Garage Entry Door'
      type: 'opening'

    2:
      name: 'Garage Back Door'
      type: 'opening'

    3:
      name: 'Front Door'
      type: 'opening'

    4:
      name: 'Back Door'
      type: 'opening'


  partitions:
    1:
      name: 'Home Alarm'

######## INCLUDES ########
group: !include groups.yaml
logbook: !include logbook.yaml
recorder: !include recorder.yaml
automation: !include_dir_merge_list automation
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include camera.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
light: !include light_group.yaml
script: !include scripts.yaml
