#################################################################
## Hardware Automation and Notifications
#################################################################

#################################################################
## Home Assistant Startup Success
#################################################################

- alias: Notification Text - Home Assistant Start

  trigger:
    - platform: homeassistant
      event: start

  action:
    - service: notify.ios_USER1_iphone
      data:
        message: "Home Assistant Started"

        #################################################################
        ## Home Assistant Started Notification
        #################################################################

- alias: Notification Log - Home Assistant Start

  trigger:
    - platform: homeassistant
      event: start
  action:
    service: system_log.write
    data:
      message: "Home Assistant started."


#################################################################
## ETH Miner HashRate Low
#################################################################

- alias: Notification Text - ETH Warning

  trigger:
    - platform: numeric_state
      entity_id: sensor.nanopoolhashrate
      below: 20
      for:
        hours: 0
        minutes: 20
        seconds: 0

  action:
    - service: notify.ios_USER1_iphone
      data:
       message: "Eth hasrate low -- {{states.sensor.nanopoolhashrate.state}}"




#################################################################
## NAS Warning
#################################################################

- alias: Notification Text - NAS Warning

  trigger:
    - platform: state
      entity_id: sensor.nas_status
      to: 'warning'

  action:
    - service: notify.ios_USER1_iphone
      data:
        message: "NAS RAID Failing"

#################################################################
## UPS Alerts
#################################################################


        ##########################################################
        ## UPS Power Loss Alert
        ##########################################################

- alias: Notification Text - UPS Power Loss Alert

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_input_voltage
      below: 80

  action:
    - service: notify.ios_USER1_iphone
      data:
        message: "Power Outage - UPS runtime {{sensor.ups_battery_runtime_mins.state}}"

        ##########################################################
        ## UPS Low Runtime Alert
        ##########################################################

- alias: Notification Text - UPS Low Runtime Alert

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_battery_runtime_mins
      below: 15

  action:
    - service: notify.ios_USER1_iphone
      data:
        message: "15 mins of UPS Battery Remaining!"
