#################################################################
## Inside Lighting Automation
#################################################################

        ##########################################################
        ## USER1 Home Turn on Lights
        ##########################################################

- alias: USER1 Home

  trigger:
    - platform: state
      entity_id: device_tracker.REDACTED
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'


  action:
    service: light.turn_on
    entity_id: light.family_room
    data:
     brightness: 255

        ##########################################################
        ## USER2 Home Turn on Lights
        ##########################################################

- alias: USER2 Home

  trigger:
    - platform: state
      entity_id: device_tracker.REDACTED
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    service: light.turn_on
    entity_id: light.family_room
    data:
     brightness: 255

        ##########################################################
        ## Pantry Light On When Door Open
        ##########################################################

- alias: Pantry Light On

  trigger:
    - platform: state
      entity_id: binary_sensor.pantry_door_opened
      from: 'off'
      to: 'on'

  action:
    service: light.turn_on
    entity_id: light.pantry_lights
    data:
     brightness: 255

        ##########################################################
        ## Pantry Light Off When Door Open
        ##########################################################

- alias: Pantry Light Off

  trigger:
    - platform: state
      entity_id: binary_sensor.pantry_door_opened
      from: 'on'
      to: 'off'

  action:
    service: light.turn_off
    entity_id: light.pantry_lights


        ##########################################################
        ## Basement Light Off When No Motion 60 Minutes
        ##########################################################

- alias: Basement Lights Off

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_motion
      from: 'on'
      to: 'off'
      for:
        hours: 1
        minutes: 0
        seconds: 0

  action:
    service: homeassistant.turn_off
    entity_id: light.basement    
