#################################################################
## Network
#################################################################

    #################################################################
    ## WAN Down Notification
    #################################################################

- alias: Network - WAN Down Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.wan
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: persistent_notification.create
      data:
        message: "Internet Down"
        title: "WAN"
        notification_id: "1"

    #################################################################
    ## WAN Up Notification
    #################################################################

- alias: Network - WAN Up Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.wan
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: persistent_notification.create
      data:
        message: "Internet Up"
        title: "WAN"
        notification_id: "1"


    #################################################################
    ## REDACTED VPN Down Notification
    #################################################################

- alias: Network - REDACTED VPN Down Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.REDACTED_vpn
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: state
      entity_id: binary_sensor.wan
      state: 'on'
  action:
    - service: notify.ios_USER1_iphone
      data:
        message: "REDACTED VPN Down"

    #################################################################
    ## REDACTED VPN Up Notification
    #################################################################

- alias: Network - REDACTED VPN Up Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.REDACTED_vpn
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
  action:
    - service: notify.ios_USER1_iphone
      data:
        message: "REDACTED VPN Up"
