##################################################################
## Outdoor Theme Automations
##################################################################

        ##########################################################
        ## Front Door Light - Set to Theme
        ##########################################################

- alias: Outdoor Theme - Front Door

  trigger:
    - platform: state
      entity_id: light.front_door
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 45
  action:
    - service: scene.turn_on
      data_template:
        entity_id: scene.front_door__{{ states.input_select.outdoor_theme.state | lower | replace(' ', '_') | replace('\'', '') }}

        ##########################################################
        ## Garage Lights - Set to Theme
        ##########################################################

- alias: Outdoor Theme - Garage

  trigger:
    - platform: state
      entity_id: light.garage
      to: 'on'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: scene.garage__{{ states.input_select.outdoor_theme.state | lower | replace(' ', '_') | replace('\'', '') }}
