#################################################################
## Outside Lighting Automation
#################################################################

        ##########################################################
        ## Turn on Outside Lights at Sunset
        ##########################################################

- alias: Outside Lights On

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:10:00'

  action:
    - service: homeassistant.turn_on
      entity_id: group.outside_lights

        ##########################################################
        ## Turn off Front and Walkout Lights at 11:30pm
        ##########################################################

- alias: Front and Walkout Lights Off

  trigger:
    - platform: time
      at: '23:30'

  action:
    - service: homeassistant.turn_off
      entity_id: light.walkout
    - service: homeassistant.turn_off
      entity_id: light.front_door

        ##########################################################
        ## Turn off Outside Lights - Outside at 4:00am
        ##########################################################

- alias: Outside Lights Off

  trigger:
    - platform: time
      at: '04:00'

  action:
    - service: homeassistant.turn_off
      entity_id: light.garage
    - service: homeassistant.turn_off
      entity_id: light.landscape
    - service: homeassistant.turn_off
      entity_id: input_boolean.party_outside

        ##########################################################
        ## Turn off Outside Lights - Outside at 4:05am
        ##########################################################

- alias: Outside Lights Off 2

  trigger:
    - platform: time
      at: '04:05'

  action:
    - service: homeassistant.turn_off
      entity_id: light.garage
    - service: homeassistant.turn_off
      entity_id: light.landscape
    - service: homeassistant.turn_off
      entity_id: input_boolean.party_outside
