#################################################################
## Outside Lighting Automation
#################################################################

        ##########################################################
        ## Turn on Outside Lights at Sunset
        ##########################################################

- alias: Outside Lights On

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:10:00'

  action:
    - service: homeassistant.turn_on
      entity_id: group.outside_lights

        ##########################################################
        ## Turn off Front and Walkout Lights at 11:30pm
        ##########################################################

- alias: Front and Walkout Lights Off

  trigger:
    - platform: time
      at: '23:30'

  action:
    - service: homeassistant.turn_off
      entity_id: light.walkout
    - service: homeassistant.turn_off
      entity_id: light.front_door

        ##########################################################
        ## Dim Landscape and Garage Lights at 11:35pm
        ##########################################################

- alias: Landscape Lights Dim

  trigger:
    - platform: time
      at: '23:35'

  action:
    - service: light.turn_on
      entity_id: light.landscape
      data:
        transition: 5
        brightness_pct: 50
    - service: light.turn_on
      entity_id: light.garage
      data:
        transition: 5
        brightness_pct: 50

        ##########################################################
        ## Turn off Outside Lights - Outside at 4:00am
        ##########################################################

- alias: Outside Lights Off

  trigger:
    - platform: time
      at: '04:00'

  action:
    - service: homeassistant.turn_off
      entity_id: light.garage
    - service: homeassistant.turn_off
      entity_id: light.landscape
    - service: homeassistant.turn_off
      entity_id: input_boolean.party_outside

        ##########################################################
        ## Turn off Outside Lights - Outside at 4:10am
        ##########################################################

- alias: Outside Lights Off 2

  trigger:
    - platform: time
      at: '04:10'

  action:
    - service: homeassistant.turn_off
      entity_id: light.garage
    - service: homeassistant.turn_off
      entity_id: light.landscape
    - service: homeassistant.turn_off
      entity_id: input_boolean.party_outside

        ##########################################################
        ## Turn Off Front Door After Hours From Motion
        ##########################################################

- alias: Front Door Lights Off

  trigger:
    - platform: state
      entity_id: light.front_door
      to: 'on'
      for:
        minutes: 15

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '23:35'
      before: '6:00'

  action:
    - service: light.turn_off
      entity_id: light.front_door
      data:
        transition: 15
