#################################################################
## Vacation Automations
#################################################################

        ##########################################################
        ## Vacation Mode Lights on at Sunset
        ##########################################################

- alias: Vacation - Lights On Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:10:00'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  action:
    - service: light.turn_on
      entity_id: light.family_room
    - service: light.turn_on
      entity_id: light.master_bedroom

        ##########################################################
        ## Vacation Mode Lights Off at 11p
        ##########################################################

- alias: Vacation - Lights Off 11p

  trigger:
    - platform: time
      at: '23:34'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'

  action:
    - service: light.turn_off
      entity_id: light.family_room
    - service: light.turn_off
      entity_id: light.master_bedroom
