#################################################################
## Water Sensor Automations
#################################################################

        ##########################################################
        ## Send Notification for Water Detected Basement
        ##########################################################

- alias: Notification - Basement Water Sensor

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'
  action:
    - service: notify.ios_USER1_iphone
      data:
        message: "Water Detected in Basement!"
    - service: notify.ios_USER2_iphone
      data:
        message: "Water Detected in Basement!"

        ##########################################################
        ## Flash Lights when Water Detected
        ##########################################################

- alias: Water Sensor - Flash Lights when Water Detected

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        brightness_pct: 100
        color_name: "blue"
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        flash: long

        ##########################################################
        ## Send Notification for Water Detected Washing Machine
        ##########################################################

- alias: Notification - Washing Machine Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: notify.ios_USER1_iphone
      data:
        message: "Water Detected by Washing Machine!"
    - service: notify.ios_USER2_iphone
      data:
        message: "Water Detected by Washing Machine!"

        ##########################################################
        ## Turn off Washing Machine when Water Detected
        ##########################################################

- alias: Water Sensor - Washing Machine Shut Off

  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.washing_machine


        ##########################################################
        ## Flash Lights when Water Detected
        ##########################################################

- alias: Water Sensor - Flash Lights when Water Detected

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.washing_machine_water_sensor
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        brightness_pct: 100
        color_name: "blue"
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        flash: long
