#################################################################
## Water Sensor Automations
#################################################################

        ##########################################################
        ## Send Notification for Water Detected Basement
        ##########################################################

- alias: Water Sensor - Basement Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: notify.hass_sns
      data:
        title: Home Assistant Notification
        message: Water Detected in Basement!
        target: !secret secret_aws_hns_arn

        ##########################################################
        ## Flash Lights when Water Detected
        ##########################################################

- alias: Water Sensor - Flash Lights when Water Detected

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        brightness_pct: 100
        color_name: "blue"
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        flash: long

        ##########################################################
        ## Send Notification for Water Detected Washing Machine
        ##########################################################

- alias: Water Sensor - Washing Machine Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: notify.hass_sns
      data:
        title: Home Assistant Notification
        message: Water Detected by Washing Machine!
        target: !secret secret_aws_hns_arn

        ##########################################################
        ## Turn off Washing Machine when Water Detected
        ##########################################################

- alias: Water Sensor - Washing Machine Shut Off

  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.washing_machine


        ##########################################################
        ## Flash Lights when Water Detected
        ##########################################################

- alias: Water Sensor - Flash Lights when Water Detected

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_water_sensor_liquid_detected
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.washing_machine_water_sensor_liquid_detected
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_sensors
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        brightness_pct: 100
        color_name: "blue"
    - service: light.turn_on
      entity_id: light.hue_lights
      data:
        flash: long
